import type {ImageSourcePropType} from 'react-native';
import type {AgeGroup, Difficulty} from '../types';

export interface RecipeData {
  id: string;
  name: string;
  description: string;
  emoji: string;
  image?: ImageSourcePropType;
  ingredients: string[];
  ingredientAmounts: string[];
  ageGroup: AgeGroup;
  cookingTime: number;
  difficulty: Difficulty;
  cookingMethod: string;
  steps: string[];
  stepTitles: string[];
}

const RECIPES: RecipeData[] = [
  // ────────────────────────────────────────
  // 초기 (6개월+) — 미음, 퓨레, 매쉬
  // ────────────────────────────────────────
  {
    id: 'e1',
    name: '쌀미음',
    description: '이유식의 시작, 가장 기본적인 쌀미음',
    emoji: '🍚',
    ingredients: ['쌀'],
    ingredientAmounts: ['불린 쌀 2큰술'],
    ageGroup: '초기',
    cookingTime: 20,
    difficulty: 'easy',
    cookingMethod: '끓이기',
    stepTitles: ['쌀 준비하기', '미음 끓이기', '체에 거르기'],
    steps: [
      '쌀을 깨끗이 씻어 30분 이상 물에 불려주세요.',
      '불린 쌀과 물 10배(쌀 1 : 물 10)를 냄비에 넣고 센 불에서 끓인 뒤, 약불로 줄여 15분간 저어가며 끓여주세요.',
      '곱게 체에 내려 물 같은 농도가 되도록 걸러주세요.',
    ],
  },
  {
    id: 'e2',
    name: '고구마 퓨레',
    description: '달콤하고 부드러운 첫 채소 이유식',
    emoji: '🍠',
    ingredients: ['고구마'],
    ingredientAmounts: ['고구마 1/2개 (약 80g)'],
    ageGroup: '초기',
    cookingTime: 15,
    difficulty: 'easy',
    cookingMethod: '찌기',
    stepTitles: ['고구마 준비', '찌기', '퓨레 만들기'],
    steps: [
      '고구마 껍질을 벗기고 작은 큐브 모양으로 잘라주세요.',
      '찜기에 올려 12~15분간 부드럽게 쪄주세요.',
      '블렌더에 넣고 물이나 분유를 조금씩 넣으며 곱게 갈아주세요.',
    ],
  },
  {
    id: 'e3',
    name: '당근 미음',
    description: '베타카로틴이 풍부한 주황빛 미음',
    emoji: '🥕',
    ingredients: ['쌀', '당근'],
    ingredientAmounts: ['불린 쌀 2큰술', '당근 20g'],
    ageGroup: '초기',
    cookingTime: 25,
    difficulty: 'easy',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '미음 끓이기', '완성'],
    steps: [
      '쌀은 30분 불리고, 당근은 껍질을 벗겨 잘게 다져주세요.',
      '불린 쌀, 당근, 물 10배를 넣고 센 불에서 끓인 뒤 약불로 20분간 끓여주세요.',
      '블렌더로 곱게 갈고 체에 한 번 걸러주세요.',
    ],
  },
  {
    id: 'e4',
    name: '단호박 퓨레',
    description: '자연 단맛이 가득한 노란 퓨레',
    emoji: '🎃',
    ingredients: ['단호박'],
    ingredientAmounts: ['단호박 80g'],
    ageGroup: '초기',
    cookingTime: 15,
    difficulty: 'easy',
    cookingMethod: '찌기',
    stepTitles: ['단호박 준비', '찌기', '퓨레 만들기'],
    steps: [
      '단호박의 씨를 제거하고 껍질을 벗겨 작게 잘라주세요.',
      '찜기에서 12~15분간 부드럽게 쪄주세요.',
      '물이나 분유를 넣으며 블렌더로 곱게 갈아주세요.',
    ],
  },
  {
    id: 'e5',
    name: '브로콜리 배 퓨레',
    description: '영양이 가득한 초록 채소 퓨레',
    emoji: '🥦',
    ingredients: ['브로콜리', '배'],
    ingredientAmounts: ['브로콜리 1컵 (꽃 부분)', '배 1/2개'],
    ageGroup: '초기',
    cookingTime: 10,
    difficulty: 'easy',
    cookingMethod: '삶기',
    stepTitles: ['재료 준비하기', '삶기', '갈기'],
    steps: [
      '브로콜리를 작은 송이로 나누고, 배는 껍질을 벗겨 잘게 썰어주세요.',
      '끓는 물에 브로콜리와 배를 8~10분간 부드러워질 때까지 삶아주세요.',
      '물기를 빼고 블렌더에 넣어 부드럽게 갈아주세요.',
    ],
  },
  {
    id: 'e6',
    name: '아보카도 바나나 매쉬',
    description: '건강한 지방이 풍부한 무조리 이유식',
    emoji: '🥑',
    ingredients: ['아보카도', '바나나'],
    ingredientAmounts: ['잘 익은 아보카도 1/2개', '잘 익은 바나나 1/2개'],
    ageGroup: '초기',
    cookingTime: 5,
    difficulty: 'easy',
    cookingMethod: '무조리',
    stepTitles: ['재료 준비하기', '으깨기'],
    steps: [
      '아보카도와 바나나의 껍질을 벗겨주세요.',
      '포크로 함께 으깨어 부드러운 매쉬를 만들어주세요.',
    ],
  },
  {
    id: 'e7',
    name: '사과 미음',
    description: '새콤달콤 사과향이 나는 미음',
    emoji: '🍎',
    ingredients: ['쌀', '사과'],
    ingredientAmounts: ['불린 쌀 2큰술', '사과 1/4개'],
    ageGroup: '초기',
    cookingTime: 25,
    difficulty: 'easy',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '미음 끓이기', '체에 거르기'],
    steps: [
      '쌀은 30분 불리고, 사과는 껍질을 벗겨 잘게 다져주세요.',
      '쌀, 사과, 물 10배를 넣고 약불에서 20분간 저어가며 끓여주세요.',
      '블렌더로 갈고 체에 걸러 완성해주세요.',
    ],
  },
  {
    id: 'e8',
    name: '감자 퓨레',
    description: '부드럽고 포슬포슬한 감자 퓨레',
    emoji: '🥔',
    ingredients: ['감자'],
    ingredientAmounts: ['감자 1/2개 (약 80g)'],
    ageGroup: '초기',
    cookingTime: 15,
    difficulty: 'easy',
    cookingMethod: '삶기',
    stepTitles: ['감자 준비', '삶기', '퓨레 만들기'],
    steps: [
      '감자 껍질을 벗기고 작게 잘라 찬물에 10분간 담가 전분을 빼주세요.',
      '끓는 물에 15분간 부드럽게 삶아주세요.',
      '물기를 빼고 으깬 뒤 물이나 분유를 넣어 농도를 맞춰주세요.',
    ],
  },
  {
    id: 'e9',
    name: '애호박 미음',
    description: '소화가 잘 되는 순한 애호박 미음',
    emoji: '🥒',
    ingredients: ['쌀', '애호박'],
    ingredientAmounts: ['불린 쌀 2큰술', '애호박 30g'],
    ageGroup: '초기',
    cookingTime: 25,
    difficulty: 'easy',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '미음 끓이기', '완성'],
    steps: [
      '쌀은 30분 불리고, 애호박은 껍질과 씨를 제거한 뒤 잘게 다져주세요.',
      '불린 쌀, 애호박, 물 10배를 넣고 약불에서 20분간 끓여주세요.',
      '블렌더로 곱게 갈아 체에 걸러주세요.',
    ],
  },
  {
    id: 'e10',
    name: '콜리플라워 퓨레',
    description: '브로콜리보다 순한 맛의 하얀 퓨레',
    emoji: '🥦',
    ingredients: ['콜리플라워'],
    ingredientAmounts: ['콜리플라워 80g (꽃 부분)'],
    ageGroup: '초기',
    cookingTime: 15,
    difficulty: 'easy',
    cookingMethod: '찌기',
    stepTitles: ['재료 준비', '찌기', '퓨레 만들기'],
    steps: [
      '콜리플라워를 작은 송이로 나눠주세요.',
      '찜기에서 12~15분간 부드럽게 쪄주세요.',
      '물이나 분유를 넣으며 블렌더로 곱게 갈아주세요.',
    ],
  },

  // ────────────────────────────────────────
  // 중기 (8개월+) — 죽, 무른 음식
  // ────────────────────────────────────────
  {
    id: 'm1',
    name: '소고기 야채죽',
    description: '단백질과 야채가 듬뿍 들어간 영양죽',
    emoji: '🍲',
    ingredients: ['쌀', '소고기', '당근', '감자'],
    ingredientAmounts: ['불린 쌀 1/4컵', '다진 소고기 30g', '당근 20g', '감자 20g'],
    ageGroup: '중기',
    cookingTime: 40,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비하기', '소고기 볶기', '죽 끓이기', '마무리'],
    steps: [
      '쌀을 30분간 물에 불리고, 소고기는 핏물을 빼고 잘게 다져주세요. 당근과 감자도 잘게 다져주세요.',
      '냄비에 참기름을 두르고 소고기를 볶아주세요.',
      '불린 쌀과 물 2컵을 넣고 끓기 시작하면 약한 불로 줄여주세요.',
      '야채를 넣고 30분간 저어가며 끓여주세요.',
    ],
  },
  {
    id: 'm2',
    name: '닭고기 브로콜리죽',
    description: '담백한 닭고기와 영양 가득 브로콜리의 만남',
    emoji: '🍗',
    ingredients: ['쌀', '닭고기', '브로콜리'],
    ingredientAmounts: ['불린 쌀 1/4컵', '닭고기 30g', '브로콜리 20g'],
    ageGroup: '중기',
    cookingTime: 35,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '닭고기 삶기', '죽 끓이기', '완성'],
    steps: [
      '쌀은 30분 불리고, 브로콜리는 꽃 부분만 잘게 다져주세요.',
      '닭고기를 삶아 건져내고 잘게 찢어주세요. 삶은 물은 육수로 사용합니다.',
      '불린 쌀과 육수를 넣고 약불에서 20분간 끓여주세요.',
      '닭고기와 브로콜리를 넣고 10분 더 끓여주세요.',
    ],
  },
  {
    id: 'm3',
    name: '두부 시금치죽',
    description: '식물성 단백질과 철분이 풍부한 죽',
    emoji: '🥬',
    ingredients: ['쌀', '두부', '시금치'],
    ingredientAmounts: ['불린 쌀 1/4컵', '연두부 30g', '시금치 잎 3장'],
    ageGroup: '중기',
    cookingTime: 30,
    difficulty: 'easy',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '시금치 데치기', '죽 끓이기'],
    steps: [
      '쌀은 30분 불리고, 두부는 으깨주세요.',
      '시금치를 끓는 물에 데쳐 찬물에 헹군 뒤 곱게 다져주세요.',
      '불린 쌀과 물 7배를 넣고 끓인 뒤 두부와 시금치를 넣고 20분간 끓여주세요.',
    ],
  },
  {
    id: 'm4',
    name: '소고기 단호박죽',
    description: '단호박의 달콤함과 소고기의 영양이 가득',
    emoji: '🎃',
    ingredients: ['쌀', '소고기', '단호박'],
    ingredientAmounts: ['불린 쌀 1/4컵', '다진 소고기 30g', '단호박 40g'],
    ageGroup: '중기',
    cookingTime: 35,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '단호박 찌기', '죽 끓이기', '완성'],
    steps: [
      '쌀은 30분 불리고, 소고기는 잘게 다져주세요.',
      '단호박은 껍질과 씨를 제거하고 쪄서 으깨주세요.',
      '참기름에 소고기를 볶고 쌀과 물을 넣어 끓여주세요.',
      '으깬 단호박을 넣고 20분간 저어가며 끓여주세요.',
    ],
  },
  {
    id: 'm5',
    name: '달걀노른자 야채죽',
    description: '완전 식품 달걀노른자가 들어간 영양죽',
    emoji: '🥚',
    ingredients: ['쌀', '달걀', '당근', '애호박'],
    ingredientAmounts: ['불린 쌀 1/4컵', '달걀 노른자 1개', '당근 15g', '애호박 15g'],
    ageGroup: '중기',
    cookingTime: 30,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '죽 끓이기', '달걀 넣기'],
    steps: [
      '쌀은 30분 불리고, 당근과 애호박은 잘게 다져주세요. 달걀은 완숙으로 삶아 노른자만 으깨주세요.',
      '쌀, 당근, 애호박, 물 7배를 넣고 약불에서 25분간 끓여주세요.',
      '으깬 노른자를 넣고 잘 저어 5분간 더 끓여주세요.',
    ],
  },
  {
    id: 'm6',
    name: '흰살생선 감자죽',
    description: '담백한 흰살생선으로 만든 부드러운 죽',
    emoji: '🐟',
    ingredients: ['쌀', '흰살생선', '감자'],
    ingredientAmounts: ['불린 쌀 1/4컵', '흰살생선 30g', '감자 30g'],
    ageGroup: '중기',
    cookingTime: 35,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '생선 삶기', '죽 끓이기'],
    steps: [
      '쌀은 30분 불리고, 감자는 잘게 다져주세요.',
      '생선을 삶아 가시를 완전히 제거하고 곱게 으깨주세요.',
      '쌀, 감자, 물 7배를 넣고 끓인 뒤 생선을 넣고 20분간 끓여주세요.',
    ],
  },
  {
    id: 'm7',
    name: '양배추 소고기죽',
    description: '소화를 돕는 양배추와 소고기의 조합',
    emoji: '🥗',
    ingredients: ['쌀', '소고기', '양배추'],
    ingredientAmounts: ['불린 쌀 1/4컵', '다진 소고기 30g', '양배추 잎 2장'],
    ageGroup: '중기',
    cookingTime: 35,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '소고기 볶기', '죽 끓이기'],
    steps: [
      '쌀은 30분 불리고, 양배추는 심을 제거하고 잘게 다져주세요.',
      '참기름에 다진 소고기를 볶아주세요.',
      '쌀, 양배추, 물 7배를 넣고 약불에서 25분간 끓여주세요.',
    ],
  },
  {
    id: 'm8',
    name: '오트밀 바나나죽',
    description: '식이섬유 풍부한 간편 오트밀 죽',
    emoji: '🌾',
    ingredients: ['오트밀', '바나나'],
    ingredientAmounts: ['오트밀 3큰술', '바나나 1/2개'],
    ageGroup: '중기',
    cookingTime: 10,
    difficulty: 'easy',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '오트밀 끓이기', '완성'],
    steps: [
      '바나나를 포크로 으깨주세요.',
      '오트밀에 물 1컵을 넣고 5분간 끓여 부드럽게 만들어주세요.',
      '으깬 바나나를 넣고 잘 섞어주세요.',
    ],
  },
  {
    id: 'm9',
    name: '고구마 사과 매쉬',
    description: '달콤한 고구마와 상큼한 사과의 조화',
    emoji: '🍠',
    ingredients: ['고구마', '사과'],
    ingredientAmounts: ['고구마 1/2개 (약 80g)', '사과 1/4개'],
    ageGroup: '중기',
    cookingTime: 20,
    difficulty: 'easy',
    cookingMethod: '찌기',
    stepTitles: ['재료 준비', '찌기', '으깨기'],
    steps: [
      '고구마와 사과의 껍질을 벗기고 작게 잘라주세요.',
      '찜기에서 12~15분간 부드럽게 쪄주세요.',
      '포크로 으깨어 부드러운 매쉬를 만들어주세요.',
    ],
  },
  {
    id: 'm10',
    name: '닭고기 당근 감자죽',
    description: '세 가지 재료로 만든 든든한 한 그릇',
    emoji: '🍗',
    ingredients: ['쌀', '닭고기', '당근', '감자'],
    ingredientAmounts: ['불린 쌀 1/4컵', '닭고기 30g', '당근 15g', '감자 15g'],
    ageGroup: '중기',
    cookingTime: 40,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '닭고기 삶기', '죽 끓이기', '완성'],
    steps: [
      '쌀은 30분 불리고, 당근과 감자는 잘게 다져주세요.',
      '닭고기를 삶아 건져내고 잘게 찢어주세요.',
      '쌀, 당근, 감자, 육수를 넣고 약불에서 25분간 끓여주세요.',
      '닭고기를 넣고 5분 더 끓여주세요.',
    ],
  },

  // ────────────────────────────────────────
  // 후기 (10개월+) — 진밥, 잘게 다진 음식
  // ────────────────────────────────────────
  {
    id: 'l1',
    name: '소고기 미역 진밥',
    description: '철분과 미네랄이 풍부한 영양 진밥',
    emoji: '🍃',
    ingredients: ['쌀', '소고기', '미역', '참기름'],
    ingredientAmounts: ['쌀 1/3컵', '다진 소고기 40g', '불린 미역 1큰술', '참기름 약간'],
    ageGroup: '후기',
    cookingTime: 35,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '소고기 볶기', '진밥 끓이기'],
    steps: [
      '미역은 물에 불려 줄기를 제거하고 잘게 다져주세요. 소고기도 잘게 다져주세요.',
      '참기름에 소고기와 미역을 볶아주세요.',
      '쌀과 물 5배를 넣고 약불에서 25분간 끓여 진밥 농도로 만들어주세요.',
    ],
  },
  {
    id: 'l2',
    name: '닭고기 채소 리조또',
    description: '여러 채소가 골고루 들어간 리조또풍 진밥',
    emoji: '🍛',
    ingredients: ['쌀', '닭고기', '당근', '양파', '브로콜리'],
    ingredientAmounts: ['쌀 1/3컵', '닭고기 40g', '당근 15g', '양파 10g', '브로콜리 15g'],
    ageGroup: '후기',
    cookingTime: 35,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '볶기', '끓이기', '완성'],
    steps: [
      '모든 재료를 잘게 다져주세요 (3~5mm 크기).',
      '올리브오일에 양파를 먼저 볶고 닭고기를 넣어 볶아주세요.',
      '쌀과 물 4배를 넣고 약불에서 20분간 끓여주세요.',
      '당근, 브로콜리를 넣고 10분 더 끓여주세요.',
    ],
  },
  {
    id: 'l3',
    name: '소고기 시금치 진밥',
    description: '철분 보충에 좋은 시금치 소고기 진밥',
    emoji: '🥬',
    ingredients: ['쌀', '소고기', '시금치', '참기름'],
    ingredientAmounts: ['쌀 1/3컵', '다진 소고기 40g', '시금치 잎 5장', '참기름 약간'],
    ageGroup: '후기',
    cookingTime: 30,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '시금치 데치기', '진밥 끓이기'],
    steps: [
      '소고기는 잘게 다지고, 시금치는 끓는 물에 데쳐 찬물에 헹궈주세요.',
      '데친 시금치를 잘게 다져주세요 (3~5mm 크기).',
      '참기름에 소고기를 볶고 쌀과 물 5배를 넣어 25분간 끓인 뒤 시금치를 넣고 5분 더 끓여주세요.',
    ],
  },
  {
    id: 'l4',
    name: '두부 버섯 덮밥',
    description: '두부와 버섯의 식감을 느끼는 덮밥',
    emoji: '🍄',
    ingredients: ['쌀', '두부', '버섯', '당근'],
    ingredientAmounts: ['진밥 1공기', '두부 50g', '양송이버섯 2개', '당근 15g'],
    ageGroup: '후기',
    cookingTime: 20,
    difficulty: 'easy',
    cookingMethod: '볶기',
    stepTitles: ['재료 준비', '볶기', '덮밥 만들기'],
    steps: [
      '두부는 으깨고, 버섯과 당근은 잘게 다져주세요 (3~5mm).',
      '팬에 올리브오일을 두르고 당근 → 버섯 → 두부 순으로 볶아주세요.',
      '진밥 위에 볶은 재료를 올려주세요.',
    ],
  },
  {
    id: 'l5',
    name: '연어 감자 매쉬',
    description: 'DHA가 풍부한 연어와 부드러운 감자',
    emoji: '🍣',
    ingredients: ['연어', '감자', '브로콜리'],
    ingredientAmounts: ['연어 40g', '감자 1/2개', '브로콜리 20g'],
    ageGroup: '후기',
    cookingTime: 25,
    difficulty: 'medium',
    cookingMethod: '삶기',
    stepTitles: ['재료 준비', '삶기', '매쉬 만들기'],
    steps: [
      '연어는 가시를 제거하고, 감자는 껍질을 벗겨 작게 잘라주세요.',
      '감자, 브로콜리, 연어를 각각 삶아주세요.',
      '감자를 으깨고 연어와 브로콜리를 잘게 다져 섞어주세요.',
    ],
  },
  {
    id: 'l6',
    name: '소고기 무죽',
    description: '소화효소가 풍부한 무와 소고기의 든든한 죽',
    emoji: '🥩',
    ingredients: ['쌀', '소고기', '무', '참기름'],
    ingredientAmounts: ['쌀 1/3컵', '다진 소고기 40g', '무 30g', '참기름 약간'],
    ageGroup: '후기',
    cookingTime: 30,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '볶기', '죽 끓이기'],
    steps: [
      '무는 껍질을 벗기고 잘게 다지고, 소고기도 잘게 다져주세요.',
      '참기름에 소고기를 볶아주세요.',
      '쌀, 무, 물 5배를 넣고 약불에서 25분간 끓여주세요.',
    ],
  },
  {
    id: 'l7',
    name: '닭고기 완두콩죽',
    description: '식물성·동물성 단백질이 함께한 한 그릇',
    emoji: '🫛',
    ingredients: ['쌀', '닭고기', '완두콩'],
    ingredientAmounts: ['쌀 1/3컵', '닭고기 40g', '완두콩 2큰술'],
    ageGroup: '후기',
    cookingTime: 35,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '닭고기 삶기', '죽 끓이기'],
    steps: [
      '완두콩은 삶아 껍질을 벗기고, 닭고기는 삶아 잘게 다져주세요.',
      '쌀과 육수를 넣고 약불에서 20분간 끓여주세요.',
      '닭고기와 완두콩을 넣고 10분 더 끓여주세요.',
    ],
  },
  {
    id: 'l8',
    name: '소고기 비트 진밥',
    description: '비트의 철분과 소고기 영양이 가득',
    emoji: '🥩',
    ingredients: ['쌀', '소고기', '비트', '양파'],
    ingredientAmounts: ['쌀 1/3컵', '다진 소고기 40g', '비트 15g', '양파 10g'],
    ageGroup: '후기',
    cookingTime: 35,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '볶기', '진밥 끓이기'],
    steps: [
      '비트와 양파는 잘게 다지고, 소고기도 다져주세요.',
      '참기름에 소고기와 양파를 볶아주세요.',
      '쌀, 비트, 물 5배를 넣고 약불에서 25분간 끓여주세요.',
    ],
  },
  {
    id: 'l9',
    name: '대구 애호박죽',
    description: '담백한 대구살과 부드러운 애호박의 조합',
    emoji: '🐟',
    ingredients: ['쌀', '대구', '애호박'],
    ingredientAmounts: ['쌀 1/3컵', '대구살 40g', '애호박 30g'],
    ageGroup: '후기',
    cookingTime: 30,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '대구 삶기', '죽 끓이기'],
    steps: [
      '대구는 가시를 완전히 제거하고, 애호박은 껍질과 씨를 제거하여 잘게 다져주세요.',
      '대구를 삶아 곱게 으깨주세요.',
      '쌀, 애호박, 물 5배를 넣고 끓인 뒤 대구를 넣고 20분간 끓여주세요.',
    ],
  },
  {
    id: 'l10',
    name: '닭고기 고구마 진밥',
    description: '달콤한 고구마와 담백한 닭고기의 조합',
    emoji: '🍗',
    ingredients: ['쌀', '닭고기', '고구마'],
    ingredientAmounts: ['쌀 1/3컵', '닭고기 40g', '고구마 40g'],
    ageGroup: '후기',
    cookingTime: 30,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '닭고기 삶기', '진밥 끓이기'],
    steps: [
      '고구마는 껍질을 벗기고 잘게 다져주세요.',
      '닭고기를 삶아 잘게 찢어주세요. 육수는 보관합니다.',
      '쌀, 고구마, 육수를 넣고 약불에서 25분간 끓인 뒤 닭고기를 넣고 5분 더 끓여주세요.',
    ],
  },

  // ────────────────────────────────────────
  // 완료기 (12개월+) — 밥, 반찬 형태
  // ────────────────────────────────────────
  {
    id: 'c1',
    name: '소고기 야채 볶음밥',
    description: '여러 채소와 소고기가 들어간 볶음밥',
    emoji: '🍚',
    ingredients: ['쌀', '소고기', '당근', '양파', '애호박', '참기름'],
    ingredientAmounts: ['밥 1공기', '다진 소고기 40g', '당근 15g', '양파 15g', '애호박 15g', '참기름 약간'],
    ageGroup: '완료기',
    cookingTime: 15,
    difficulty: 'easy',
    cookingMethod: '볶기',
    stepTitles: ['재료 준비', '볶기', '밥 볶기'],
    steps: [
      '모든 야채와 소고기를 5mm 크기로 잘게 다져주세요.',
      '참기름에 소고기를 볶다가 야채를 넣어 볶아주세요.',
      '밥을 넣고 골고루 섞이도록 볶아주세요.',
    ],
  },
  {
    id: 'c2',
    name: '달걀 야채전',
    description: '한 입 크기로 만든 부드러운 야채전',
    emoji: '🥚',
    ingredients: ['달걀', '당근', '애호박', '양파'],
    ingredientAmounts: ['달걀 1개', '당근 10g', '애호박 10g', '양파 5g'],
    ageGroup: '완료기',
    cookingTime: 15,
    difficulty: 'easy',
    cookingMethod: '굽기',
    stepTitles: ['재료 준비', '반죽 만들기', '부치기'],
    steps: [
      '당근, 애호박, 양파를 곱게 다져주세요.',
      '달걀을 풀고 다진 야채를 넣어 섞어주세요.',
      '팬에 올리브오일을 두르고 한 큰술씩 올려 약불에서 양면을 노릇하게 부쳐주세요.',
    ],
  },
  {
    id: 'c3',
    name: '두부 채소 볶음',
    description: '부드러운 두부와 여러 채소의 반찬',
    emoji: '🧈',
    ingredients: ['두부', '당근', '양파', '애호박', '참기름'],
    ingredientAmounts: ['두부 1/2모', '당근 15g', '양파 10g', '애호박 15g', '참기름 약간'],
    ageGroup: '완료기',
    cookingTime: 10,
    difficulty: 'easy',
    cookingMethod: '볶기',
    stepTitles: ['재료 준비', '두부 볶기', '야채 넣기'],
    steps: [
      '두부는 1cm 크기로 깍둑썰기, 야채는 5mm 크기로 다져주세요.',
      '팬에 참기름을 두르고 두부를 노릇하게 볶아주세요.',
      '야채를 넣고 2~3분간 함께 볶아주세요.',
    ],
  },
  {
    id: 'c4',
    name: '닭고기 채소 수프',
    description: '따뜻하고 영양 가득한 닭고기 수프',
    emoji: '🍲',
    ingredients: ['닭고기', '감자', '당근', '양파', '브로콜리'],
    ingredientAmounts: ['닭고기 50g', '감자 1/4개', '당근 15g', '양파 10g', '브로콜리 15g'],
    ageGroup: '완료기',
    cookingTime: 30,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '닭고기 삶기', '수프 끓이기', '완성'],
    steps: [
      '모든 재료를 7~8mm 크기로 잘라주세요.',
      '닭고기를 삶아 잘게 찢어주세요. 육수는 보관합니다.',
      '육수에 감자, 당근, 양파를 넣고 15분간 끓여주세요.',
      '브로콜리와 닭고기를 넣고 5분 더 끓여주세요.',
    ],
  },
  {
    id: 'c5',
    name: '소고기 김치볶음밥 (아기용)',
    description: '잘 익은 김치를 씻어 만든 순한 볶음밥',
    emoji: '🍚',
    ingredients: ['쌀', '소고기', '양파', '참기름'],
    ingredientAmounts: ['밥 1공기', '다진 소고기 40g', '양파 15g', '참기름 약간'],
    ageGroup: '완료기',
    cookingTime: 15,
    difficulty: 'easy',
    cookingMethod: '볶기',
    stepTitles: ['재료 준비', '볶기', '완성'],
    steps: [
      '소고기와 양파를 잘게 다져주세요.',
      '참기름에 소고기와 양파를 볶아주세요.',
      '밥을 넣고 골고루 볶아주세요.',
    ],
  },
  {
    id: 'c6',
    name: '생선 채소찜',
    description: '부드러운 흰살생선과 채소를 함께 찐 건강식',
    emoji: '🐟',
    ingredients: ['흰살생선', '감자', '당근', '브로콜리'],
    ingredientAmounts: ['흰살생선 50g', '감자 30g', '당근 15g', '브로콜리 15g'],
    ageGroup: '완료기',
    cookingTime: 20,
    difficulty: 'easy',
    cookingMethod: '찌기',
    stepTitles: ['재료 준비', '찌기', '완성'],
    steps: [
      '생선의 가시를 완전히 제거하고 한 입 크기로 잘라주세요. 채소도 적당한 크기로 잘라주세요.',
      '찜기에 감자 → 당근 → 생선 → 브로콜리 순서로 올려 15분간 쪄주세요.',
      '잘 익었는지 확인하고 아기가 먹기 좋은 크기로 잘라주세요.',
    ],
  },
  {
    id: 'c7',
    name: '치즈 달걀말이',
    description: '칼슘 풍부한 치즈가 들어간 부드러운 달걀말이',
    emoji: '🧀',
    ingredients: ['달걀', '치즈', '당근'],
    ingredientAmounts: ['달걀 2개', '아기용 치즈 1장', '당근 10g'],
    ageGroup: '완료기',
    cookingTime: 10,
    difficulty: 'easy',
    cookingMethod: '굽기',
    stepTitles: ['재료 준비', '달걀물 만들기', '말아 굽기'],
    steps: [
      '당근은 곱게 다지고, 치즈는 잘게 찢어주세요.',
      '달걀을 풀고 당근과 치즈를 넣어 섞어주세요.',
      '팬에 올리브오일을 두르고 약불에서 얇게 펴 말아가며 구워주세요.',
    ],
  },
  {
    id: 'c8',
    name: '새우 볶음밥',
    description: '새우의 감칠맛이 가득한 볶음밥',
    emoji: '🦐',
    ingredients: ['쌀', '새우', '달걀', '당근', '양파', '참기름'],
    ingredientAmounts: ['밥 1공기', '새우 4~5마리', '달걀 1개', '당근 10g', '양파 10g', '참기름 약간'],
    ageGroup: '완료기',
    cookingTime: 15,
    difficulty: 'medium',
    cookingMethod: '볶기',
    stepTitles: ['재료 준비', '새우 볶기', '볶음밥 만들기'],
    steps: [
      '새우는 껍질과 내장을 제거하고 잘게 다져주세요. 당근, 양파도 잘게 다져주세요.',
      '참기름에 새우를 먼저 볶고 야채를 넣어 볶아주세요.',
      '밥과 풀어둔 달걀을 넣고 골고루 볶아 완성해주세요.',
    ],
  },
  {
    id: 'c9',
    name: '소고기 토마토 파스타',
    description: '부드러운 토마토 소스의 아기 파스타',
    emoji: '🍝',
    ingredients: ['소고기', '토마토', '양파', '당근'],
    ingredientAmounts: ['다진 소고기 40g', '토마토 1개', '양파 10g', '당근 10g'],
    ageGroup: '완료기',
    cookingTime: 30,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '토마토 소스 만들기', '소고기 넣기', '완성'],
    steps: [
      '토마토는 끓는 물에 데쳐 껍질과 씨를 제거해주세요. 양파와 당근은 잘게 다져주세요.',
      '올리브오일에 양파를 볶다가 토마토와 당근을 넣고 10분간 끓여주세요.',
      '다진 소고기를 넣고 10분간 더 끓여주세요.',
      '잘게 자른 파스타면 위에 소스를 올려주세요.',
    ],
  },
  {
    id: 'c10',
    name: '돼지고기 김 볶음밥',
    description: '김의 고소함과 돼지고기가 어우러진 볶음밥',
    emoji: '🍃',
    ingredients: ['쌀', '돼지고기', '김', '당근', '참기름'],
    ingredientAmounts: ['밥 1공기', '다진 돼지고기 30g', '무조미 김 1장', '당근 10g', '참기름 약간'],
    ageGroup: '완료기',
    cookingTime: 15,
    difficulty: 'easy',
    cookingMethod: '볶기',
    stepTitles: ['재료 준비', '볶기', '완성'],
    steps: [
      '돼지고기는 잘게 다지고, 당근도 잘게 다져주세요. 김은 잘게 부숴주세요.',
      '참기름에 돼지고기와 당근을 볶은 뒤 밥을 넣고 볶아주세요.',
      '불을 끄고 부순 김을 섞어주세요.',
    ],
  },
  {
    id: 'c11',
    name: '돼지고기 감자조림',
    description: '달콤짭짤한 간장 맛의 부드러운 감자조림',
    emoji: '🥔',
    ingredients: ['돼지고기', '감자', '당근', '양파'],
    ingredientAmounts: ['돼지고기 안심 50g', '감자 1개', '당근 1/4개', '양파 1/4개'],
    ageGroup: '완료기',
    cookingTime: 25,
    difficulty: 'medium',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '볶기', '조리기'],
    steps: [
      '감자와 당근은 1cm 크기로, 양파는 잘게 다져주세요. 돼지고기도 작게 잘라주세요.',
      '팬에 돼지고기와 양파를 볶아주세요.',
      '감자, 당근, 물 1/2컵을 넣고 뚜껑을 덮어 15분간 약불에서 조려주세요.',
    ],
  },
  {
    id: 'c12',
    name: '연어 채소 주먹밥',
    description: '한 입 크기로 만든 영양 주먹밥',
    emoji: '🍙',
    ingredients: ['쌀', '연어', '당근', '김', '참기름'],
    ingredientAmounts: ['밥 1공기', '연어 40g', '당근 10g', '무조미 김 1장', '참기름 약간'],
    ageGroup: '완료기',
    cookingTime: 15,
    difficulty: 'easy',
    cookingMethod: '굽기',
    stepTitles: ['재료 준비', '섞기', '주먹밥 만들기'],
    steps: [
      '연어는 구워서 가시를 제거하고 잘게 부숴주세요. 당근은 다져서 살짝 볶고, 김은 잘게 부숴주세요.',
      '밥에 연어, 당근, 김, 참기름을 넣고 골고루 섞어주세요.',
      '한 입 크기로 동그랗게 굴려 주먹밥을 만들어주세요.',
    ],
  },
  {
    id: 'c13',
    name: '소고기 미역국',
    description: '아기를 위한 순한 미역국',
    emoji: '🍃',
    ingredients: ['소고기', '미역', '참기름'],
    ingredientAmounts: ['다진 소고기 40g', '불린 미역 2큰술', '참기름 약간'],
    ageGroup: '완료기',
    cookingTime: 25,
    difficulty: 'easy',
    cookingMethod: '끓이기',
    stepTitles: ['재료 준비', '볶기', '끓이기'],
    steps: [
      '미역은 물에 불려 줄기를 제거하고 잘게 잘라주세요. 소고기는 잘게 다져주세요.',
      '참기름에 소고기와 미역을 2~3분간 볶아주세요.',
      '물 2컵을 넣고 20분간 끓여주세요.',
    ],
  },
  {
    id: 'c14',
    name: '닭고기 버섯 덮밥',
    description: '버섯의 감칠맛과 닭고기의 고소한 덮밥',
    emoji: '🍄',
    ingredients: ['쌀', '닭고기', '버섯', '양파', '당근'],
    ingredientAmounts: ['밥 1공기', '닭고기 50g', '양송이버섯 3개', '양파 10g', '당근 10g'],
    ageGroup: '완료기',
    cookingTime: 20,
    difficulty: 'easy',
    cookingMethod: '볶기',
    stepTitles: ['재료 준비', '닭고기 볶기', '덮밥 완성'],
    steps: [
      '닭고기는 잘게 다지고, 버섯·양파·당근은 먹기 좋은 크기로 잘라주세요.',
      '팬에 올리브오일을 두르고 닭고기를 볶다가 야채를 넣어 함께 볶아주세요.',
      '밥 위에 올려 완성해주세요.',
    ],
  },
];

export function getAllRecipes(): RecipeData[] {
  return RECIPES;
}

export function getRecipeById(id: string): RecipeData | undefined {
  return RECIPES.find(r => r.id === id);
}
